
[compiler.solc]
via_IR = true
remappings = [
  "forge-std/=lib/forge-std/src/",
  "ds-test/=lib/forge-std/lib/ds-test/src/",
  "@safe-contracts=lib/safe-contracts/contracts",
  "@openzeppelin=lib/openzeppelin-contracts/contracts",
  "@solmate=lib/solmate/src",
  "solenv=lib/solenv/src",
  "@create3=lib/create3-factory/src/"
]
[compiler.solc.optimizer]
# enabled (unset - let the compiler decide)
runs = 200